### PR TITLE
Fix create user validation logic

### LINKED ISSUE #2554: Create User Validation
The modal can be submitted with validation issues. Submission should be blocked until validation

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes #2554

### CODE REVIEW

File: resources/js/admin/users/components/AddUserModal.vue [hunk 1]
```diff
@@ -66,31 +66,26 @@ export default {
...
-                            + ' "' + this.username + '" ' + 
-                            this.$t('would you like to save and reactivate their account?')
-                        ]);
-                        let restoreData = {
-                            username: this.username
-                        };
-                        this.showMsgBox(messageVNode, restoreData);
+
+                let deletedUserExists = false;
+                for (const key of ['username', 'email']) {
```
Comment (velkymx) [inline resources/js/admin/users/components/AddUserModal.vue]: Why const?

File: ProcessMaker/Models/User.php [hunk 2]
```diff
@@ -135,8 +135,16 @@ public static function rules($existing = null)
         $unique = Rule::unique('users')->ignore($existing);
 
         $checkUserIsDeleted = function($attribute, $value, $fail) use ($existing) {
-            if (!$existing && User::where($attribute, $value)->exists()) {
-                $fail('userExists');
+            if (!$existing) {
+                $user = User::withTrashed()->where($attribute, $value)->first();
```
Comment (sanjacornelius) [inline ProcessMaker/Models/User.php]: When adding a non-deleted user the 'Deleted User Found' modal appears. 
Changing `withTrashed()` to `onlyTrashed()` appears to fix the issue.

`withTrashed()`: returns all records including trashed

`onlyTrashed()`: returns only the trashed records

https://laravel.com/docs/6.x/scout#soft-deleting
